#!/usr/bin/env bash
set -euo pipefail

ref="${1:-}"
dst="${2:?destination sysroot required}"
strict="${3:-auto}"

required_paths=(
    "libexec/webkit2gtk-4.1/MiniBrowser"
    "libexec/webkit2gtk-4.1/WebKitNetworkProcess"
    "libexec/webkit2gtk-4.1/WebKitWebProcess"
    "libexec/webkit2gtk-4.1/jsc"
    "lib/libwebkit2gtk-4.1.so"
    "lib/libjavascriptcoregtk-4.1.so"
    "lib/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so"
)

remove_staged_webkit() {
    mkdir -p "${dst}/libexec/webkit2gtk-4.1"
    rm -rf \
        "${dst}/lib/webkit2gtk-4.1" \
        "${dst}/include/webkitgtk-4.1"
    rm -f \
        "${dst}/bin/jsc" \
        "${dst}/lib/libwebkit2gtk-4.1.so"* \
        "${dst}/lib/libjavascriptcoregtk-4.1.so"* \
        "${dst}/lib/pkgconfig/webkit2gtk-4.1.pc" \
        "${dst}/lib/pkgconfig/webkit2gtk-web-extension-4.1.pc" \
        "${dst}/lib/pkgconfig/javascriptcoregtk-4.1.pc" \
        "${dst}/libexec/webkit2gtk-4.1/MiniBrowser" \
        "${dst}/libexec/webkit2gtk-4.1/WebKitNetworkProcess" \
        "${dst}/libexec/webkit2gtk-4.1/WebKitWebProcess" \
        "${dst}/libexec/webkit2gtk-4.1/jsc" \
        "${dst}/libexec/webkit2gtk-4.1/.webkit_install_stamp"
}

if [[ -z "${ref}" || ! -x "${ref}/libexec/webkit2gtk-4.1/MiniBrowser" ]]; then
    if [[ "${strict}" == "1" || "${strict}" == "ON" || "${strict}" == "TRUE" ]]; then
        echo "ports/webkit: ${ref} does not contain a runnable WebKitGTK runtime" >&2
        exit 1
    fi
    echo "ports/webkit: warning: ${ref} does not contain WebKitGTK; skipping stage" >&2
    remove_staged_webkit
    touch "${dst}/libexec/webkit2gtk-4.1/.webkit-stage.stamp"
    exit 0
fi

missing=()
for rel in "${required_paths[@]}"; do
    if [[ ! -e "${ref}/${rel}" ]]; then
        missing+=("${rel}")
    fi
done
if ((${#missing[@]})); then
    printf 'ports/webkit: incomplete WebKitGTK runtime at %s\n' "${ref}" >&2
    printf '  missing: %s\n' "${missing[@]}" >&2
    exit 1
fi

mkdir -p \
    "${dst}/bin" \
    "${dst}/include" \
    "${dst}/lib" \
    "${dst}/lib/gio/modules" \
    "${dst}/lib/pkgconfig" \
    "${dst}/lib/webkit2gtk-4.1" \
    "${dst}/libexec" \
    "${dst}/share"

remove_staged_webkit

copy_glob() {
    local pattern="$1"
    local matches=()
    shopt -s nullglob
    matches=( ${pattern} )
    shopt -u nullglob
    if ((${#matches[@]})); then
        cp -a "${matches[@]}" "${dst}/lib/"
    fi
}

lib_patterns=(
    "${ref}/lib/libwebkit2gtk-4.1.so"*
    "${ref}/lib/libjavascriptcoregtk-4.1.so"*
    "${ref}/lib/libnghttp2.so"*
    "${ref}/lib/libgtk-3.so"*
    "${ref}/lib/libgdk-3.so"*
    "${ref}/lib/libgdk_pixbuf-2.0.so"*
    "${ref}/lib/libgio-2.0.so"*
    "${ref}/lib/libgobject-2.0.so"*
    "${ref}/lib/libglib-2.0.so"*
    "${ref}/lib/libgmodule-2.0.so"*
    "${ref}/lib/libpangocairo-1.0.so"*
    "${ref}/lib/libpango-1.0.so"*
    "${ref}/lib/libpangoft2-1.0.so"*
    "${ref}/lib/libatk-1.0.so"*
    "${ref}/lib/libcairo-gobject.so"*
    "${ref}/lib/libcairo.so"*
    "${ref}/lib/libepoxy.so"*
    "${ref}/lib/libfontconfig.so"*
    "${ref}/lib/libfreetype.so"*
    "${ref}/lib/libpixman-1.so"*
    "${ref}/lib/libpng16.so"*
    "${ref}/lib/libfribidi.so"*
    "${ref}/lib/libxkbcommon.so"*
    "${ref}/lib/libffi.so"*
    "${ref}/lib/libatomic.so"*
    "${ref}/lib/libstdc++.so"*
    "${ref}/lib/libgcc_s.so"*
)

for pattern in "${lib_patterns[@]}"; do
    copy_glob "${pattern}"
done

if [[ -e "${ref}/lib/gio/modules/libgioopenssl.so" ]]; then
    cp -a "${ref}/lib/gio/modules/libgioopenssl.so" "${dst}/lib/gio/modules/"
fi
if [[ -e "${ref}/lib/gio/modules/giomodule.cache" ]]; then
    cp -a "${ref}/lib/gio/modules/giomodule.cache" "${dst}/lib/gio/modules/"
fi

mkdir -p "${dst}/libexec/webkit2gtk-4.1"
rm -f "${dst}/libexec/webkit2gtk-4.1/MiniBrowser.bak"
for exe in MiniBrowser WebKitNetworkProcess WebKitWebProcess jsc; do
    if [[ -x "${ref}/libexec/webkit2gtk-4.1/${exe}" ]]; then
        cp -a "${ref}/libexec/webkit2gtk-4.1/${exe}" \
              "${dst}/libexec/webkit2gtk-4.1/"
    fi
done
if [[ -e "${ref}/libexec/webkit2gtk-4.1/.webkit_install_stamp" ]]; then
    cp -a "${ref}/libexec/webkit2gtk-4.1/.webkit_install_stamp" \
          "${dst}/libexec/webkit2gtk-4.1/"
fi
cp -a "${ref}/lib/webkit2gtk-4.1" "${dst}/lib/"

if [[ -d "${ref}/include/webkitgtk-4.1" ]]; then
    cp -a "${ref}/include/webkitgtk-4.1" "${dst}/include/"
fi
if [[ -d "${ref}/include/libsoup-3.0" ]]; then
    cp -a "${ref}/include/libsoup-3.0" "${dst}/include/"
fi
for pc in \
    webkit2gtk-4.1.pc \
    webkit2gtk-web-extension-4.1.pc \
    javascriptcoregtk-4.1.pc \
    libsoup-3.0.pc
do
    if [[ -e "${ref}/lib/pkgconfig/${pc}" ]]; then
        cp -a "${ref}/lib/pkgconfig/${pc}" "${dst}/lib/pkgconfig/"
    fi
done

if [[ -x "${ref}/bin/jsc" ]]; then
    cp -a "${ref}/bin/jsc" "${dst}/bin/"
fi

{
    echo "# Generated by ports/webkit/stage-webkit-runtime.sh"
    echo "source=${ref}"
    find "${dst}/lib" "${dst}/libexec/webkit2gtk-4.1" \
        \( -name 'libwebkit2gtk-4.1.so*' \
        -o -name 'libjavascriptcoregtk-4.1.so*' \
        -o -path "${dst}/lib/webkit2gtk-4.1/*" \
        -o -path "${dst}/libexec/webkit2gtk-4.1/*" \) \
        -printf '%P\n' | sort
} > "${dst}/libexec/webkit2gtk-4.1/.webkit-stage-manifest"

touch "${dst}/libexec/webkit2gtk-4.1/.webkit-stage.stamp"
